<?php
/**
 * Created by PhpStorm.
 * User: leogent <leogent@gmail.com>
 * Date: 2/4/19
 * Time: 12:21 AM
 */

namespace Doku\Core\Block\Adminhtml;


class Recurring extends \Magento\Backend\Block\Widget\Grid\Container
{

    protected function _construct()
    {
        $this->_controller = 'adminhtml_recurring'; /* block grid.php directory */
        $this->_blockGroup = 'Doku_Core';
        $this->_headerText = __('Recurring');
        $this->_addButtonLabel = __('Add New Entry');

        parent::_construct(); // TODO: Change the autogenerated stub
    }

}